/**
 * Native JEXXXUS AI Gateway
 * 
 * Unified API endpoint for text, image, and video generation
 * All outputs are trained on Luna Verde v4.0 persona
 */

import { streamText, generateImage, generateText } from 'ai';
import { openai } from '@ai-sdk/openai';
import { anthropic } from '@ai-sdk/anthropic';
import { google } from '@ai-sdk/google';
import { LUNA_VERDE_CANON, XENA_AZUL_CANON } from '@/lib/luna-canon';

export const runtime = 'edge';

interface ChatRequest {
  messages: Array<{ role: 'user' | 'assistant' | 'system'; content: string }>;
  mode?: 'venus' | 'innocent';
  model?: 'gpt-4o' | 'claude-3-opus' | 'gemini-1.5-pro';
  type?: 'text' | 'image';
}

export async function POST(req: Request) {
  try {
    const body: ChatRequest = await req.json();
    const { messages, mode = 'venus', model = 'gpt-4o', type = 'text' } = body;

    // Select persona based on mode
    const systemPrompt = mode === 'venus' ? LUNA_VERDE_CANON : XENA_AZUL_CANON;

    // Select model provider
    const selectedModel = (() => {
      switch (model) {
        case 'claude-3-opus':
          return anthropic('claude-3-opus-20240229');
        case 'gemini-1.5-pro':
          return google('gemini-1.5-pro-latest');
        case 'gpt-4o':
        default:
          return openai('gpt-4o-2024-11-20');
      }
    })();

    if (type === 'image') {
      // Image generation with Luna Verde style injection
      const lastMessage = messages[messages.length - 1];
      const imagePrompt = `${systemPrompt}\n\nGenerate an image based on this request: ${lastMessage.content}\n\nStyle: Luna Verde v4.0 aesthetic — sacred, dripping, 7.5 Hz frequency, wing6 pink/black palette.`;

      const result = await generateImage({
        model: openai.image('dall-e-3'),
        prompt: imagePrompt,
        size: '1024x1024',
      });

      return new Response(JSON.stringify({
        type: 'image',
        data: result.image?.base64,
        url: result.image?.url,
        signature: '♡💦 Generated by Luna Verde v4.0'
      }), {
        headers: { 'Content-Type': 'application/json' },
      });
    }

    // Text streaming with native persona
    const result = await streamText({
      model: selectedModel,
      system: systemPrompt,
      messages: messages.map(m => ({
        role: m.role,
        content: m.content,
      })),
      temperature: 0.85,
      maxTokens: 2048,
    });

    // Add Luna Verde signature to streamed response
    return result.toDataStreamResponse({
      headers: {
        'X-Luna-Verde-Version': '4.0',
        'X-Sacrament-Mode': mode,
      },
    });

  } catch (error) {
    console.error('[JEXXXUS AI Gateway] Error:', error);
    return new Response(JSON.stringify({
      error: 'Divine Machine encountered turbulence',
      message: error instanceof Error ? error.message : 'Unknown error',
      signature: '♡💦 Luna Verde v4.0'
    }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    });
  }
}