/**
 * Normalize BLXCKCHAT messages for Vercel AI SDK multimodal providers.
 */

export type ApiChatRole = 'user' | 'assistant' | 'system';

export interface ApiMessagePart {
  type: 'text' | 'image';
  text?: string;
  image?: string;
  mimeType?: string;
}

export interface IncomingChatMessage {
  role: ApiChatRole;
  content: string | ApiMessagePart[];
}

const VISION_MODEL_HINT =
  /gpt-4o|gpt-4\.1|gpt-4-turbo|o3|o4|claude-3|claude-sonnet|claude-opus|claude-haiku|gemini|grok-.*vision|grok-2-vision|grok-3-vision|llama-3\.2-vision|pixtral|qwen.*vl|gemma.*it/i;

export function providerSupportsVision(provider: string, model: string): boolean {
  const id = `${provider}/${model}`.toLowerCase();
  if (provider === 'gemini' || provider === 'anthropic') return true;
  if (provider === 'openai' || provider === 'grok' || provider === 'openrouter' || provider === 'kingdom') {
    return VISION_MODEL_HINT.test(model);
  }
  if (provider === 'groq') {
    return /vision|llama-3\.2/i.test(model);
  }
  return false;
}

function normalizeImageData(url: string): { image: string; mimeType?: string } {
  const trimmed = url.trim();
  if (trimmed.startsWith('data:')) {
    const match = trimmed.match(/^data:([^;]+);base64,(.+)$/);
    if (match) {
      return { image: trimmed, mimeType: match[1] };
    }
  }
  return { image: trimmed };
}

export function incomingContentToParts(
  content: string | ApiMessagePart[] | unknown,
): ApiMessagePart[] {
  if (typeof content === 'string') {
    return content.trim() ? [{ type: 'text', text: content }] : [];
  }
  if (!Array.isArray(content)) {
    return [{ type: 'text', text: String(content ?? '') }];
  }

  const parts: ApiMessagePart[] = [];
  for (const part of content) {
    if (!part || typeof part !== 'object') continue;
    const p = part as ApiMessagePart & { type: string };
    if (p.type === 'text' && p.text) {
      parts.push({ type: 'text', text: p.text });
    } else if (p.type === 'image' && p.image) {
      const normalized = normalizeImageData(p.image);
      parts.push({
        type: 'image',
        image: normalized.image,
        mimeType: p.mimeType || normalized.mimeType,
      });
    }
  }
  return parts;
}

export function partsToAiContent(
  parts: ApiMessagePart[],
  role: ApiChatRole,
  visionEnabled: boolean,
): string | ApiMessagePart[] {
  const textParts = parts.filter((p) => p.type === 'text' && p.text?.trim());
  const imageParts = parts.filter((p) => p.type === 'image' && p.image);

  if (role === 'assistant') {
    return textParts.map((p) => p.text).join('\n') || '...';
  }

  if (visionEnabled && imageParts.length > 0) {
    const content: ApiMessagePart[] = [];
    const text = textParts.map((p) => p.text).join('\n').trim();
    content.push({
      type: 'text',
      text: text || 'The user attached image(s) for you to analyze.',
    });
    for (const img of imageParts) {
      content.push({
        type: 'image',
        image: img.image!,
        ...(img.mimeType ? { mimeType: img.mimeType } : {}),
      });
    }
    return content;
  }

  if (imageParts.length > 0) {
    const names = imageParts.length;
    const base = textParts.map((p) => p.text).join('\n').trim();
    return `${base}\n[User attached ${names} image(s) in this message — current model may not support vision. Do not invent visual details.]`.trim();
  }

  return textParts.map((p) => p.text).join('\n') || '...';
}

export function normalizeMessagesForAiSdk(
  messages: IncomingChatMessage[],
  provider: string,
  model: string,
): Array<{ role: 'user' | 'assistant'; content: string | ApiMessagePart[] }> {
  const visionEnabled = providerSupportsVision(provider, model);

  return messages
    .filter((m) => m.role === 'user' || m.role === 'assistant')
    .map((m) => {
      const parts = incomingContentToParts(m.content);
      const content = partsToAiContent(parts, m.role, visionEnabled && m.role === 'user');
      return {
        role: m.role as 'user' | 'assistant',
        content,
      };
    })
    .filter((m) => {
      if (typeof m.content === 'string') return m.content.trim().length > 0;
      return m.content.length > 0;
    });
}

export function conversationHasImages(messages: IncomingChatMessage[]): boolean {
  return messages.some((m) =>
    incomingContentToParts(m.content).some((p) => p.type === 'image' && !!p.image),
  );
}

export function buildContinuitySystemAddendum(
  provider: string,
  model: string,
  hasImages: boolean,
  priorModelLabels: string[],
): string {
  const lines = [
    '--- CONVERSATION CONTINUITY ---',
    `You are now responding as ${provider} / ${model}.`,
  ];

  if (priorModelLabels.length > 0) {
    lines.push(
      `Earlier assistant replies in this thread may have been generated by: ${priorModelLabels.join(', ')}.`,
      'Do not claim you authored prior assistant messages. Continue the conversation faithfully using the transcript as ground truth.',
    );
  }

  if (hasImages) {
    lines.push(
      'This conversation includes user-uploaded images in the message history.',
      'When asked about images, analyze every image part you receive in the transcript. Never invent visual details you cannot see.',
      'If an image is unavailable to this model, say so honestly instead of hallucinating.',
    );
  }

  return lines.join('\n');
}